apiVersion: apps/v1
kind: Deployment
metadata:
  name: productlookup
  labels:
    app: productlookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productlookup
  template:
    metadata:
      labels:
        app: productlookup
    spec:
      containers:
      - image: productlookup
        name: productlookup
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: 'productlookup'
        - name: SPLUNK_METRICS_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):9943"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=splunksecuritytshirtco-prod'
        - name: OTEL_PROPAGATORS
          value: 'b3multi'
---
apiVersion: v1
kind: Service
metadata:
  name: productlookup
spec:
  type: NodePort
  selector:
    app: productlookup
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002
