apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplierservice
  labels:
    app: supplierservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplierservice
  template:
    metadata:
      labels:
        app: supplierservice
    spec:
      containers:
      - image: supplierservice
        name: supplierservice
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: 'supplierservice'
        - name: SPLUNK_METRICS_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):9943"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=frothly-eks'
        - name: OTEL_PROPAGATORS
          value: 'b3multi'
---
apiVersion: v1
kind: Service
metadata:
  name: supplierservice
spec:
  type: NodePort
  selector:
    app: supplierservice
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30033